app/gamehub/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', include('links.urls')),
    path('admin/', admin.site.urls),
]

app/links/urls.py
from django.urls import path

from links import views


app_name = 'links'
urlpatterns = [
    path('', views.LinkListView.as_view(), name='links-list'),
    path('add/', views.LinkAddFormView.as_view(), name='links-add'),
    path('delete/<int:pk>/', views.LinkDeleteFormView.as_view(), name='links-delete'),

    path('check/<int:pk>/', views.check, name='links-check')
]

app/links/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Link(models.Model):
    user = models.ForeignKey(
        get_user_model(), 
        blank=False, null=False,
        on_delete=models.CASCADE, # delete links on user delete
    )
    created = models.DateTimeField(
        null=True, blank=True,
        auto_now_add=True,
    )
    url = models.URLField(max_length=256)
    check_interval = models.PositiveIntegerField(blank=True, null=False, default=60*60*5)
    

app/links/forms.py
from django import forms

from links.models import Link


class LinkForm(forms.ModelForm):

    class Meta:
        model = Link
        fields = ['url', 'check_interval']

app/links/views.py
import requests
import json

from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import Http404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse

from links.models import Link
from links.forms import LinkForm


class LinkListView(LoginRequiredMixin, ListView):
    template_name = 'links/links_list.html'
    model = Link
    paginate_by = 20

    def get_queryset(self):
        return Link.objects.filter(user=self.request.user).order_by('-created')


class LinkAddFormView(LoginRequiredMixin, CreateView):
    template_name = 'links/links_add.html'
    form_class = LinkForm

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        return super(LinkAddFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('links:links-list')


class LinkDeleteFormView(LoginRequiredMixin, DeleteView):
    model = Link

    def get_queryset(self):
        return Link.objects.filter(user=self.request.user) #.filter(user=self.request.user)

    def get_success_url(self):
        return reverse('links:links-list')


@login_required
def check(request, pk):
    if not pk:
        return HttpResponseBadRequest(
            json.dumps({'error': '`url` param is not provided in url.'}), 
            content_type="application/json"
        )

    link = Link.objects.filter(user=request.user, pk=pk).first()
    if not link:
        raise Http404

    status_code = -1
    try:
        response = requests.get(link.url)
        status_code = response.status_code
    except requests.ConnectionError:
        pass

    return HttpResponse(
        json.dumps({'status': status_code, 'pk': link.pk}), 
        content_type="application/json"
    )

app/links/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% block style %}
  {% endblock style %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'links:links-list' %}">Logo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'links:links-list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'links:links-add' %}">Add new link</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

  {% block javascript %}
  {% endblock javascript %}

</body>

</html>

app/links/templates/links/links_add.html
{% extends "base.html" %}

<!-- {% load static %} -->

{% block content %}
<div class="row">
  <div class="col-12 col-md-6">
    <form method="post" action="" name="" class="mt-5">
      <div class="">
        <p class="h4">Добавить ссылку</p>
      </div>
      <div class="mt-4">
        {% csrf_token %}
        {% for field in form %}
        {% if field.errors %}
        <ul>
          {% for err in field.errors %}
          <li>{{ err }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        <div class="form-group">
          <div class="row">
            <div class="col-5">
              <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
            </div>
            <div class="col-7">
              <input type="text" class="form-control" value="" id="{{ field.auto_id }}" name="{{ field.name }}">
            </div>
          </div>
        </div>
        {% endfor %}
        {% if non_field_errors.errors %}
        <ul>
          {% for err in non_field_errors.errors %}
          <li>{{ err }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        <input type="submit" value="Добавить" class="submit-btn btn btn-primary"></input>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

app/links/templates/links/links_list.html
{% extends "base.html" %}

{% block content %}
<table class="table mt-5">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">created at</th>
      <th scope="col">url</th>
      <th scope="col">check_interval</th>
      <th scope="col">status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for link in object_list %}
    <tr class="links-to-check" data-interval="{{ link.check_interval }}" data-url="{% url 'links:links-check' link.pk %}">
      <td>{{ link.pk }}</td>
      <td>{{ link.created }}</td>
      <td>{{ link.url }}</td>
      <td>{{ link.check_interval }}</td>
      <td class="link-status"></td>
      <td>
        <form method="POST" action="{% url 'links:links-delete' link.pk %}">
          {% csrf_token %}
          <input type="submit" value="delete" class="btn btn-primary">
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

{% block javascript %}
<script>
  $().ready(function () {
    $('.links-to-check').each(function () {
      var $instance = $(this);
      let period = $instance.data('interval');   
      let urlToCheck = $instance.data('url');
      setInterval(function () {
        $.ajax(urlToCheck)
        .done(function (res) {
          $instance.find('.link-status').text(res.status);
          if (res.status === 200) {
            $instance.addClass('table-success');
            $instance.removeClass('table-danger');
          } else {
            $instance.addClass('table-danger');
            $instance.removeClass('table-success');
          }
        })
        .fail(function (error) {
          console.log(error.responseText)
        })
      }, period);
    })
  })
</script>
{% endblock javascript %}